API_KEY = 'IM6rY9ffWSKfl36MhVsgRc6vI'
API_SECRET = 'Hz6PKwWRUvhUNNXJ7X4K2rmvRYGesSRt4OGyn0HOJCyyRANZeB'
ACCESS_TOKEN = '1329983514536669205-7PoMb4fKwkhS3H6mNubCY81kLfZ0MD'
ACCESS_TOKEN_SECRET = 'Xcq9t5acK99Y08pFvhUVIYO3QGaJeJY8Sy8pJ6F19HV6f'

NEWS_KEY="c3d8cb4b8e834bf1850416917d71dd4d"